markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Base URI for your site, e.g. http://example.com/test-repo/ => for development leave empty for gh-pages fill in the name of the repo of not the main gh-pages repo
base_url: "" 

# Main title for your site --> TODO investigate and document where this is actually used
title: "Data VLIZ"
logo: "/assets/media/img/VLIZ_LOGO_OpSci.svg"

# social_media refs to be included in the footer 
# Not included in the footer
social_media:
  - name: github
    url: https://github.com/vlizbe/


# Enables global share buttons to twitter (X), facebook, printer, email, linkedIn | default true
share_enabled: false

# used ruby gems for building this jekyll based site
gems:
  - jekyll-mermaid              # allows mermaid diagrams included in ```mermaid blocks in md
plugins:
  - jekyll-datapage-generator   # TODO investigate and document why this is here
  - jemoji                      # allows :emoji-name: inline images in markdown